name1=input("pick a name ")
adjective=input("pick an adjective ")
adverb=input("pick an adverb ")
verb=input("pick a verb ")
noun1=input("pick a noun ")
noun2=input("pick a second noun ")
noun3=input("pick a third noun ")
name2=input("pick a second name ")
print(f"{name1} was picking out a gift for their friend's kid {name2}.Their birthday party.")
print(f"{name1} had three choices, {noun1}, {noun2} and {noun3}.")
print(f"{name1} had decided to pick {noun1} as {name1} went to grab it, someone else went to grab it and {name1} had to {verb} to get there before the other person".)
print(f" when {name1} got to the party, it was very {adjective})
print(f"when {name1} gave {name2} their gift,they had a {adverb} level of happieness.")
