noun=input("Pick a noun")
adjective1=input("pick one adjective ")
adjective2=input("pick a second adjective ")
food1=input("pick a food ")
food2=input("pick a second food ")
name=input("pick a name ")
place=input("pick a place ")
adverb=input("pick and adverb ")
verb=input("pick a verb ")
print(f"{name} was planning a dream vacation to {place}.")
print(f"{name} was especially looking forward to trying the local cuisine, including {adjective1} {food1} {food2}.")
print(f"{name} will have to practice the language {adverb} to make it easier to {verb} with people.")
print(f"{name} has a long list of sights to see, including the {noun} museum and the {adjective2} park.")
